version: "3.8"

services:
    database:
        image: mariadb:latest
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: cinephoria
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"

    analytics:
        # The "latest" ES version is not used here because the Backend's node client must use the same version
        # You're free to upgrade ES, but don't forget to update the Backend's node client at the same version
        image: elasticsearch:9.0.1
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
            xpack.security.enabled: 'false'

    analytics-init:
        build: analytics
        links:
            - analytics
        depends_on:
            - analytics

    http:
        image: nginx:latest
        volumes:
            - ./website/build/:/var/www/website
            - ./mobile/build/:/var/www/mobile
            - ./desktop/build/:/var/www/desktop
            - ./static/:/var/www/static
            - ./http/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf/:/etc/nginx/ssl
            # Certbot will put files here for the ACME challenge
            - ./certbot/www/:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
