version: "3.8"

services:
    database:
        image: mariadb:latest
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: cinephoria
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"

    analytics:
        image: elasticsearch:8.14.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
            xpack.security.enabled: 'false'

    analytics-init:
        build: analytics
        links:
            - analytics
        depends_on:
            - analytics
